"""Add review relation to user table

Revision ID: dcca9f7bbb35
Revises: 3abd5e91a7be
Create Date: 2025-01-02 14:02:29.618760

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dcca9f7bbb35'
down_revision = '3abd5e91a7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
