"""Add order table

Revision ID: ea985c2c7ff8
Revises: f28c80dd85b2
Create Date: 2025-01-01 17:25:14.666077

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea985c2c7ff8'
down_revision = 'f28c80dd85b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
