"""Add payment flow tables

Revision ID: eccc5e157037
Revises: fcfed32d7551
Create Date: 2025-01-03 14:21:11.464601

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eccc5e157037'
down_revision = 'fcfed32d7551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('address_type', sa.Enum('BILLING', 'SHIPPING', name='addresstype'), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    py = postgresql.ENUM('STRIPE', 'PAYPAL', name='paymentmethod')
    py.create(op.get_bind())
    op.add_column('order', sa.Column('payment_method', sa.Enum('STRIPE', 'PAYPAL', name='paymentmethod'), nullable=True))
    op.add_column('order', sa.Column('billing_address_id', sa.Uuid(), nullable=True))
    op.add_column('order', sa.Column('shipping_address_id', sa.Uuid(), nullable=True))
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               nullable=True)
    op.create_foreign_key(None, 'order', 'address', ['shipping_address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order', 'address', ['billing_address_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order', 'available_quantity')
    op.drop_column('order', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               nullable=False)
    op.drop_column('order', 'shipping_address_id')
    op.drop_column('order', 'billing_address_id')
    py = postgresql.ENUM('STRIPE', 'PAYPAL', name='paymentmethod')
    py.drop(op.get_bind())
    op.drop_column('order', 'payment_method')
    op.drop_table('orderitem')
    op.drop_table('cartitem')
    op.drop_table('cart')
    op.drop_table('address')
    # ### end Alembic commands ###
