"""Remove items from user

Revision ID: ee1af39f5304
Revises: 916767d42bf4
Create Date: 2025-01-01 21:10:38.066210

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee1af39f5304'
down_revision = '916767d42bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'customer_id')
    # ### end Alembic commands ###
