"""Make product images optional

Revision ID: fcfed32d7551
Revises: 78a9243d76b6
Create Date: 2025-01-02 17:07:32.720981

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fcfed32d7551'
down_revision = '78a9243d76b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
